"""
Pydantic data models for verification test specifications and evaluation results.

Three models form the data layer for the semantic verification system:

  VerificationTestSpec       — defines a single test (generated once per question by the LLM plan)
  VerificationTestResult     — outcome of evaluating one spec against a SQL candidate
  VerificationEvaluation     — aggregated results + confidence adjustment for one candidate
"""
from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class VerificationTestSpec(BaseModel):
    """A single verification test generated by the LLM for a given question."""
    test_type: str
    """One of: grain|null|duplicate|ordering|scale|
    column_alignment|boundary|symmetry"""
    description: str = ""
    """Human-readable description of what this test checks.
    Only required for boundary (used in the LLM judge prompt)."""
    verification_sql: Optional[str] = None
    """Direct SQL query against the raw database (NOT a template wrapping the
    candidate SQL). Used for grain, duplicate, and symmetry tests."""
    check_columns: list[str] = Field(default_factory=list)
    """For null test: column names to check for NULLs in result rows."""
    required_sql_keywords: list[str] = Field(default_factory=list)
    """For ordering test: SQL keywords/clauses that must be present
    (e.g. ['ORDER BY', 'LIMIT'])."""
    order_by_column: Optional[str] = None
    """For ordering test: the metric/ranking column to use in ORDER BY
    (e.g. 'score', 'total_sales', 'gpa'). None when not set by plan LLM."""
    order_by_direction: Optional[str] = None
    """For ordering test: 'DESC' for highest/best/most, 'ASC' for lowest/worst/least."""
    order_limit: Optional[int] = None
    """For ordering test: the N from 'top N' / 'N highest' in the question."""
    expected_row_count: Optional[int] = None
    """Deprecated. Use row_count_min/row_count_max or verification_sql_upper instead."""
    verification_sql_upper: Optional[str] = None
    """For grain test: SQL returning an integer upper bound on result rows
    (e.g. SELECT COUNT(DISTINCT id) FROM students).
    For grain only; verification_sql continues to serve duplicate/symmetry tests."""
    row_count_min: Optional[int] = None
    """For grain test: static lower bound. When None, effective lower is 1
    (enforced with max(value, 1)). Empty results are always wrong."""
    row_count_max: Optional[int] = None
    """For grain test: static integer upper bound when no bounding SQL is available."""
    expected_column_count: Optional[int] = None
    """For column_alignment test (canonical) or grain test (legacy):
    expected number of output columns.
    1 for scalar/aggregate results, 2+ for multi-column outputs."""
    column_descriptions: list[str] = Field(default_factory=list)
    """For column_alignment test: one short semantic label per expected SELECT column
    (e.g. ['student name', 'enrollment count']). Length equals expected_column_count."""
    numeric_min: Optional[float] = None
    """For scale test: minimum expected value for numeric result columns."""
    numeric_max: Optional[float] = None
    """For scale test: maximum expected value for numeric result columns."""
    expected_outcome: str = ""
    """Human-readable description of what a PASS looks like.
    Only required for boundary (used in the LLM judge prompt)."""
    fix_hint: str = ""
    """Actionable hint for the SQL fixer if this test fails."""


class VerificationTestResult(BaseModel):
    """Outcome of evaluating one VerificationTestSpec against a candidate."""
    test_type: str
    status: str           # "pass" | "fail" | "skip" | "error"
    actual_outcome: str   # What was observed
    is_critical: bool
    computed_upper_bound: Optional[int] = None  # grain: resolved upper bound row count
    actual_row_count: Optional[int] = None      # grain: actual result row count


class VerificationEvaluation(BaseModel):
    """Aggregated verification results for one SQL candidate."""
    candidate_id: str
    test_results: list[VerificationTestResult]
    all_pass: bool                 # True if no "fail" results
    confidence_adjustment: float   # Penalty/bonus to add to raw confidence score
    failure_hints: list[str]       # Formatted hints for the fixer's combined prompt
