"""
Semantic Verification for SQL Candidates (integrated into Op 8 fix loop).

QueryVerifier has two responsibilities:

  1. generate_plan() — one LLM call (model_powerful) per question; returns a list
     of VerificationTestSpec objects describing applicable semantic checks.
     Called once in QueryFixer.fix_candidates() before the per-candidate loop.

  2. evaluate_candidate() — evaluates all specs against a specific SQL
     candidate's execution result; mostly free (SQLite execution + structural
     analysis); expensive LLM-judgment tests run on every iteration.

Test types:

  Cheap (no LLM cost):
    grain         — result row count matches expected entity count
    null          — result rows contain no unexpected NULL values
    duplicate     — JOIN did not multiply rows beyond expected distinct count
    ordering      — "top N / highest / ranked" questions have ORDER BY + LIMIT
    scale         — numeric result values are within expected range

  Expensive (1 LLM call each, run every iteration):
    column_alignment — SELECT columns actually answer the question
    boundary         — date/time constraints match the question's period
    symmetry         — aggregate total matches sum of sub-groups
"""
from __future__ import annotations

import logging
import re
from typing import Optional

from pydantic import BaseModel, Field

from src.config.settings import settings
from src.data.database import ExecutionResult, execute_sql
from src.llm import CacheableText, LLMError, get_client
from src.llm.base import ToolParam, sanitize_prompt_text

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Confidence adjustment constants
# ---------------------------------------------------------------------------

_PENALTY_CRITICAL = -0.3   # per critical test failure
_PENALTY_MINOR = -0.1      # per minor test failure
_BONUS_ALL_PASS = 0.2      # bonus when ALL applicable tests pass (capped)
_MAX_BONUS = 0.2

_CHEAP_TESTS = frozenset({
    "grain", "null", "duplicate", "ordering", "scale"
})
_EXPENSIVE_TESTS = frozenset({
    "column_alignment", "boundary", "symmetry"
})
_ALL_TEST_TYPES = _CHEAP_TESTS | _EXPENSIVE_TESTS


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

class VerificationTestSpec(BaseModel):
    """A single verification test generated by the LLM for a given question."""
    test_type: str
    """One of: grain|null|duplicate|ordering|scale|
    column_alignment|boundary|symmetry"""
    description: str
    """Human-readable description of what this test checks."""
    verification_sql: Optional[str] = None
    """Direct SQL query against the raw database (NOT a template wrapping the
    candidate SQL). Used for grain, duplicate, and symmetry tests."""
    check_columns: list[str] = Field(default_factory=list)
    """For null test: column names to check for NULLs in result rows."""
    required_sql_keywords: list[str] = Field(default_factory=list)
    """For ordering test: SQL keywords/clauses that must be present
    (e.g. ['ORDER BY', 'LIMIT'])."""
    expected_row_count: Optional[int] = None
    """Deprecated. Use row_count_min/row_count_max or verification_sql_upper instead."""
    verification_sql_upper: Optional[str] = None
    """For grain test: SQL returning an integer upper bound on result rows
    (e.g. SELECT COUNT(DISTINCT id) FROM students).
    For grain only; verification_sql continues to serve duplicate/symmetry tests."""
    row_count_min: Optional[int] = None
    """For grain test: static lower bound. When None, effective lower is 1
    (enforced with max(value, 1)). Empty results are always wrong."""
    row_count_max: Optional[int] = None
    """For grain test: static integer upper bound when no bounding SQL is available."""
    expected_column_count: Optional[int] = None
    """For grain test: expected number of output columns.
    1 for scalar/aggregate results, 2+ for multi-column outputs."""
    numeric_min: Optional[float] = None
    """For scale test: minimum expected value for numeric result columns."""
    numeric_max: Optional[float] = None
    """For scale test: maximum expected value for numeric result columns."""
    expected_outcome: str
    """Human-readable description of what a PASS looks like."""
    fix_hint: str
    """Actionable hint for the SQL fixer if this test fails."""
    is_critical: bool = False
    """Critical tests (grain, duplicate, column_alignment) penalize -0.3;
    minor tests penalize -0.1."""


class VerificationTestResult(BaseModel):
    """Outcome of evaluating one VerificationTestSpec against a candidate."""
    test_type: str
    status: str           # "pass" | "fail" | "skip" | "error"
    actual_outcome: str   # What was observed
    is_critical: bool


class VerificationEvaluation(BaseModel):
    """Aggregated verification results for one SQL candidate."""
    candidate_id: str
    test_results: list[VerificationTestResult]
    all_pass: bool                 # True if no "fail" results
    confidence_adjustment: float   # Penalty/bonus to add to raw confidence score
    failure_hints: list[str]       # Formatted hints for the fixer's combined prompt


# ---------------------------------------------------------------------------
# Tool schema for plan generation
# ---------------------------------------------------------------------------

_PLAN_TOOL = ToolParam(
    name="verification_plan",
    description=(
        "Generate a list of semantic verification tests for the given SQL question. "
        "Only include tests that are genuinely applicable to this specific question."
    ),
    input_schema={
        "type": "object",
        "properties": {
            "tests": {
                "type": "array",
                "description": "Verification tests to run on every SQL candidate for this question.",
                "items": {
                    "type": "object",
                    "properties": {
                        "test_type": {
                            "type": "string",
                            "enum": sorted(_ALL_TEST_TYPES),
                        },
                        "description": {"type": "string"},
                        "verification_sql": {
                            "type": "string",
                            "description": (
                                "Optional direct SQLite query against the database "
                                "(NOT wrapping the candidate SQL). Used for "
                                "duplicate and symmetry tests."
                            ),
                        },
                        "verification_sql_upper": {
                            "type": "string",
                            "description": (
                                "For grain test: SQL returning an integer upper bound on result rows "
                                "(e.g. SELECT COUNT(DISTINCT id) FROM students). "
                                "Represents the maximum rows a correct answer could have."
                            ),
                        },
                        "row_count_min": {
                            "type": "integer",
                            "description": (
                                "For grain test: minimum expected result rows. Default is 1. "
                                "Only set higher when you are certain at least N rows must exist."
                            ),
                        },
                        "row_count_max": {
                            "type": "integer",
                            "description": (
                                "For grain test: static integer upper bound when no bounding SQL "
                                "is available. Prefer verification_sql_upper when possible."
                            ),
                        },
                        "expected_column_count": {
                            "type": "integer",
                            "description": (
                                "For grain test: expected number of output columns. "
                                "1 for scalar/aggregate results, 2+ for multi-column outputs. "
                                "Omit if unsure."
                            ),
                        },
                        "check_columns": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "For null test: column names to check for NULLs.",
                        },
                        "required_sql_keywords": {
                            "type": "array",
                            "items": {"type": "string"},
                            "description": "For ordering test: SQL keywords that must be present.",
                        },
                        "numeric_min": {
                            "type": "number",
                            "description": "For scale test: minimum expected numeric value.",
                        },
                        "numeric_max": {
                            "type": "number",
                            "description": "For scale test: maximum expected numeric value.",
                        },
                        "expected_outcome": {"type": "string"},
                        "fix_hint": {
                            "type": "string",
                            "description": "Specific, actionable hint for fixing the SQL if this test fails.",
                        },
                        "is_critical": {
                            "type": "boolean",
                            "description": (
                                "True for logical errors (grain, duplicate, column_alignment). "
                                "False for style/quality issues."
                            ),
                        },
                    },
                    "required": [
                        "test_type", "description", "expected_outcome",
                        "fix_hint", "is_critical",
                    ],
                },
            }
        },
        "required": ["tests"],
    },
)

_PLAN_SYSTEM = CacheableText(
    text=(
        "You are an expert SQL quality analyst. Given a natural-language question "
        "and a database schema, generate a concise set of semantic verification "
        "tests that any correct SQL answer to this question should pass.\n\n"
        "Test types and when to use each:\n\n"
        "grain: If the question expects a bounded number of result rows (e.g. 'for "
        "each student', 'per department', 'how many', 'average'), generate a grain test.\n"
        "  - Set verification_sql_upper to a SQL COUNT query giving the maximum plausible "
        "rows (e.g. SELECT COUNT(DISTINCT id) FROM students). This runs against the raw DB.\n"
        "  - Set row_count_min only if you are certain at least N>1 rows must exist; "
        "otherwise leave it unset (default is 1 — empty results are always wrong).\n"
        "  - Set expected_column_count: 1 for scalar/aggregate ('how many', 'what is "
        "the average'), 2 for name+value pairs, more for explicit multi-column outputs. "
        "Omit if unsure.\n"
        "  - Mark is_critical=true.\n\n"
        "null: If key output columns should not be NULL (e.g. names, IDs), list "
        "those column names in check_columns. Mark is_critical=false.\n\n"
        "duplicate: If the query involves JOINs across multiple tables, generate a "
        "verification_sql counting DISTINCT primary key entities to detect row "
        "multiplication. Mark is_critical=true.\n\n"
        "ordering: If the question uses 'top N', 'highest', 'lowest', 'ranked', "
        "'best', or 'worst', set required_sql_keywords to ['ORDER BY', 'LIMIT']. "
        "Mark is_critical=false.\n\n"
        "scale: If numeric values have known bounds (percentages: 0-100, ages: "
        "0-120, ratings: 0-5), set numeric_min and numeric_max. Mark is_critical=false.\n\n"
        "column_alignment: Always include this to verify SELECT columns answer the "
        "question. This is LLM-judged. Mark is_critical=true.\n\n"
        "boundary: Only include if the question mentions specific dates, years, or "
        "time periods. Mark is_critical=false.\n\n"
        "symmetry: Only include if the question asks for a total that should equal "
        "the sum of sub-groups (e.g. 'total = active + inactive'). Generate a "
        "verification_sql for the sub-total check. Mark is_critical=false.\n\n"
        "RULES:\n"
        "- Include 2-5 tests maximum. Quality over quantity.\n"
        "- Only include tests that are genuinely applicable to THIS question.\n"
        "- verification_sql must be valid SQLite querying the raw database tables.\n"
        "- fix_hint must be concrete and mention specific SQL clauses to add/change.\n"
    ),
    cache=True,
)


# ---------------------------------------------------------------------------
# QueryVerifier
# ---------------------------------------------------------------------------

class QueryVerifier:
    """
    Generates and evaluates semantic verification plans for SQL candidates.

    Workflow::

        verifier = QueryVerifier()

        # Once per question:
        specs = await verifier.generate_plan(question, evidence, schema)

        # Per candidate, per fix iteration:
        eval_result = await verifier.evaluate_candidate(
            specs, candidate_id, sql, exec_result, db_path,
            run_expensive=(iteration == beta)  # True only on final check
        )
    """

    async def generate_plan(
        self,
        question: str,
        evidence: str,
        schema: str,
    ) -> list[VerificationTestSpec]:
        """
        Generate applicable verification tests for this question.

        Makes exactly 1 LLM call (model_powerful). Returns an empty list on any
        failure — verification is optional and never blocks the fix loop.
        """
        q = sanitize_prompt_text(question)
        ev = sanitize_prompt_text(evidence or "None")
        schema_abbrev = schema[:3000]  # abbreviate for very large schemas

        user_msg = (
            f"Question: {q}\n"
            f"Evidence: {ev}\n\n"
            f"Database Schema:\n{schema_abbrev}\n\n"
            "Generate the verification tests for this question."
        )

        try:
            client = get_client()
            response = await client.generate(
                model=settings.model_powerful,
                system=[_PLAN_SYSTEM],
                messages=[{"role": "user", "content": user_msg}],
                tools=[_PLAN_TOOL],
                tool_choice_name="verification_plan",
                temperature=0.0,
                max_tokens=1500,
            )
            if not response.tool_inputs:
                logger.warning("Verification plan LLM returned no tool inputs")
                return []
            raw_tests = response.tool_inputs[0].get("tests", [])
            specs: list[VerificationTestSpec] = []
            for t in raw_tests:
                try:
                    spec = VerificationTestSpec(**t)
                    if spec.test_type in _ALL_TEST_TYPES:
                        specs.append(spec)
                    else:
                        logger.warning("Unknown test_type %r in plan — skipped", spec.test_type)
                except Exception as e:
                    logger.warning("Failed to parse VerificationTestSpec: %s", e)
            return specs
        except LLMError as exc:
            logger.warning("Verification plan generation failed (LLMError): %s", exc)
            return []
        except Exception as exc:
            logger.warning("Unexpected error in generate_plan: %s", exc)
            return []

    async def evaluate_candidate(
        self,
        specs: list[VerificationTestSpec],
        candidate_id: str,
        sql: str,
        exec_result: ExecutionResult,
        db_path: str,
        run_expensive: bool = False,
    ) -> VerificationEvaluation:
        """
        Evaluate all applicable specs against a SQL candidate.

        Parameters
        ----------
        specs:
            Tests generated by generate_plan().
        candidate_id:
            Generator ID for logging.
        sql:
            Current SQL (after any preceding fix iterations).
        exec_result:
            Latest execution result for this SQL.
        db_path:
            Path to the SQLite database for running verification queries.
        run_expensive:
            If True, also run LLM-judgment tests (column_alignment, boundary,
            symmetry). Always True — parameter kept for interface compatibility.
        """
        results: list[VerificationTestResult] = []

        for spec in specs:
            is_expensive = spec.test_type in _EXPENSIVE_TESTS
            if is_expensive and not run_expensive:
                continue  # Skip expensive tests on early iterations

            if not exec_result.success:
                # Cannot evaluate semantic tests without a valid execution result
                results.append(VerificationTestResult(
                    test_type=spec.test_type,
                    status="skip",
                    actual_outcome="Skipped — SQL did not execute successfully.",
                    is_critical=spec.is_critical,
                ))
                continue

            result = await self._evaluate_single(spec, sql, exec_result, db_path)
            results.append(result)

        all_pass = all(r.status in ("pass", "skip", "error") for r in results)
        adjustment = self._compute_adjustment(results)
        failure_hints = [
            f"{r.test_type.upper()} TEST FAILED: {r.actual_outcome}  "
            f"Hint: {self._get_hint(r.test_type, specs)}"
            for r in results if r.status == "fail"
        ]

        return VerificationEvaluation(
            candidate_id=candidate_id,
            test_results=results,
            all_pass=all_pass,
            confidence_adjustment=adjustment,
            failure_hints=failure_hints,
        )

    def _get_hint(self, test_type: str, specs: list[VerificationTestSpec]) -> str:
        for spec in specs:
            if spec.test_type == test_type:
                return spec.fix_hint
        return "Review the SQL logic."

    async def _evaluate_single(
        self,
        spec: VerificationTestSpec,
        sql: str,
        exec_result: ExecutionResult,
        db_path: str,
    ) -> VerificationTestResult:
        """Dispatch to the appropriate evaluation method."""
        tt = spec.test_type
        try:
            if tt == "grain":
                return self._eval_grain(spec, exec_result, db_path)
            elif tt == "null":
                return self._eval_null(spec, exec_result)
            elif tt == "duplicate":
                return self._eval_duplicate(spec, exec_result, db_path)
            elif tt == "ordering":
                return self._eval_ordering(spec, sql)
            elif tt == "scale":
                return self._eval_scale(spec, exec_result)
            elif tt == "column_alignment":
                return await self._eval_column_alignment(spec, sql, exec_result)
            elif tt == "boundary":
                return await self._eval_boundary(spec, sql)
            elif tt == "symmetry":
                return self._eval_symmetry(spec, exec_result, db_path)
            else:
                return VerificationTestResult(
                    test_type=tt,
                    status="skip",
                    actual_outcome=f"Unknown test type: {tt}",
                    is_critical=spec.is_critical,
                )
        except Exception as exc:
            logger.warning("Error evaluating %r test for candidate: %s", tt, exc)
            return VerificationTestResult(
                test_type=tt,
                status="error",
                actual_outcome=f"Evaluation error: {exc}",
                is_critical=spec.is_critical,
            )

    # ------------------------------------------------------------------
    # Cheap test implementations
    # ------------------------------------------------------------------

    def _eval_grain(
        self,
        spec: VerificationTestSpec,
        exec_result: ExecutionResult,
        db_path: str,
    ) -> VerificationTestResult:
        """Grain test: check result row count is within [lower, upper] and
        optionally that column count matches expected."""
        actual_count = len(exec_result.rows)

        # ── 1. Resolve upper bound ──────────────────────────────────────────
        upper: Optional[int] = None

        if spec.verification_sql_upper:
            vr = execute_sql(db_path, spec.verification_sql_upper)
            if vr.success and vr.rows and isinstance(vr.rows[0][0], (int, float)):
                upper = int(vr.rows[0][0])
        elif spec.verification_sql:
            # Backward compat: old verification_sql treated as upper bound for grain
            vr = execute_sql(db_path, spec.verification_sql)
            if vr.success and vr.rows and isinstance(vr.rows[0][0], (int, float)):
                upper = int(vr.rows[0][0])
        elif spec.row_count_max is not None:
            upper = spec.row_count_max
        elif spec.expected_row_count is not None:
            # Legacy exact-match: treat as upper = expected
            upper = spec.expected_row_count

        # ── 2. Resolve lower bound (minimum is always 1) ───────────────────
        lower: int = max(spec.row_count_min if spec.row_count_min is not None else 1, 1)

        # ── 3. Row count check ─────────────────────────────────────────────
        row_count_ok: Optional[bool] = None
        row_count_msg: str = ""

        if upper is not None:
            if lower <= actual_count <= upper:
                row_count_ok = True
                row_count_msg = (
                    f"Row count {actual_count} is within range [{lower}, {upper}]."
                )
            elif actual_count < lower:
                row_count_ok = False
                row_count_msg = (
                    f"Row count {actual_count} is below minimum {lower}. "
                    "Result may be too restrictive or missing rows."
                )
            else:
                row_count_ok = False
                row_count_msg = (
                    f"Row count {actual_count} exceeds upper bound {upper}. "
                    "Possible wrong grain or missing GROUP BY / DISTINCT."
                )
        else:
            # No upper bound — only enforce lower
            if actual_count >= lower:
                row_count_ok = True
                row_count_msg = f"Row count {actual_count} meets minimum {lower}."
            else:
                row_count_ok = False
                row_count_msg = (
                    f"Row count {actual_count} is below minimum {lower} "
                    "(empty results are always wrong)."
                )

        # ── 4. Column count check (independent of row count) ───────────────
        col_count_ok: Optional[bool] = None
        col_count_msg: str = ""

        if spec.expected_column_count is not None and exec_result.rows:
            actual_cols = len(exec_result.rows[0])
            if actual_cols == spec.expected_column_count:
                col_count_ok = True
                col_count_msg = (
                    f"Column count {actual_cols} matches expected "
                    f"{spec.expected_column_count}."
                )
            else:
                col_count_ok = False
                col_count_msg = (
                    f"Column count {actual_cols} does not match expected "
                    f"{spec.expected_column_count}. Check SELECT list."
                )

        # ── 5. Combine results ─────────────────────────────────────────────
        if row_count_ok is None and col_count_ok is None:
            return VerificationTestResult(
                test_type="grain",
                status="skip",
                actual_outcome="No grain bounds or expected column count specified.",
                is_critical=spec.is_critical,
            )

        row_fail = row_count_ok is False
        col_fail = col_count_ok is False

        if row_fail or col_fail:
            parts = []
            if row_fail:
                parts.append(row_count_msg)
            if col_fail:
                parts.append(col_count_msg)
            return VerificationTestResult(
                test_type="grain",
                status="fail",
                actual_outcome=" | ".join(parts),
                is_critical=spec.is_critical,
            )

        parts = []
        if row_count_ok is True:
            parts.append(row_count_msg)
        if col_count_ok is True:
            parts.append(col_count_msg)
        return VerificationTestResult(
            test_type="grain",
            status="pass",
            actual_outcome=" | ".join(parts),
            is_critical=spec.is_critical,
        )

    def _eval_null(
        self,
        spec: VerificationTestSpec,
        exec_result: ExecutionResult,
    ) -> VerificationTestResult:
        """Null test: check result rows for unexpected NULL values."""
        rows = exec_result.rows
        if not rows:
            return VerificationTestResult(
                test_type="null",
                status="skip",
                actual_outcome="No rows to check for NULLs.",
                is_critical=spec.is_critical,
            )

        null_count = sum(1 for row in rows for val in row if val is None)
        total_cells = sum(len(row) for row in rows)

        if null_count == 0:
            return VerificationTestResult(
                test_type="null",
                status="pass",
                actual_outcome=f"No NULL values in {len(rows)} result rows.",
                is_critical=spec.is_critical,
            )
        null_pct = (null_count / total_cells * 100) if total_cells > 0 else 0
        return VerificationTestResult(
            test_type="null",
            status="fail",
            actual_outcome=(
                f"Found {null_count} NULL values across {len(rows)} rows "
                f"({null_pct:.1f}% of cells). May indicate missing JOIN conditions."
            ),
            is_critical=spec.is_critical,
        )

    def _eval_duplicate(
        self,
        spec: VerificationTestSpec,
        exec_result: ExecutionResult,
        db_path: str,
    ) -> VerificationTestResult:
        """Duplicate test: detect JOIN-induced row multiplication."""
        actual_count = len(exec_result.rows)

        if spec.verification_sql:
            vr = execute_sql(db_path, spec.verification_sql)
            if vr.success and vr.rows and isinstance(vr.rows[0][0], (int, float)):
                expected = int(vr.rows[0][0])
                if expected > 0:
                    ratio = actual_count / expected
                    if ratio >= 2.0:
                        return VerificationTestResult(
                            test_type="duplicate",
                            status="fail",
                            actual_outcome=(
                                f"Result has {actual_count} rows but expected ~{expected} "
                                f"distinct entities (ratio: {ratio:.1f}x). "
                                "JOIN may be multiplying rows."
                            ),
                            is_critical=spec.is_critical,
                        )
                    return VerificationTestResult(
                        test_type="duplicate",
                        status="pass",
                        actual_outcome=(
                            f"Row count {actual_count} vs expected {expected} "
                            "— no JOIN multiplication detected."
                        ),
                        is_critical=spec.is_critical,
                    )

        # Fallback: check for exact duplicate rows in result
        if exec_result.rows:
            try:
                unique_rows = len(set(exec_result.rows))
            except TypeError:
                # Rows contain unhashable types (e.g. lists) — skip
                return VerificationTestResult(
                    test_type="duplicate",
                    status="skip",
                    actual_outcome="Result rows contain unhashable values — skipped.",
                    is_critical=spec.is_critical,
                )
            if unique_rows < actual_count:
                dup_count = actual_count - unique_rows
                return VerificationTestResult(
                    test_type="duplicate",
                    status="fail",
                    actual_outcome=(
                        f"Found {dup_count} duplicate rows ({actual_count} total, "
                        f"{unique_rows} unique). JOIN may be creating duplicates."
                    ),
                    is_critical=spec.is_critical,
                )
            return VerificationTestResult(
                test_type="duplicate",
                status="pass",
                actual_outcome=f"All {actual_count} rows are unique — no duplicates.",
                is_critical=spec.is_critical,
            )

        return VerificationTestResult(
            test_type="duplicate",
            status="skip",
            actual_outcome="No rows to check for duplicates.",
            is_critical=spec.is_critical,
        )

    def _eval_ordering(
        self,
        spec: VerificationTestSpec,
        sql: str,
    ) -> VerificationTestResult:
        """Ordering test: structural check that required SQL clauses are present."""
        required = spec.required_sql_keywords or ["ORDER BY", "LIMIT"]
        sql_upper = sql.upper()
        missing = [kw for kw in required if kw.upper() not in sql_upper]

        if not missing:
            return VerificationTestResult(
                test_type="ordering",
                status="pass",
                actual_outcome=f"All required clauses present: {required}.",
                is_critical=spec.is_critical,
            )
        return VerificationTestResult(
            test_type="ordering",
            status="fail",
            actual_outcome=f"Missing required SQL clauses: {missing}.",
            is_critical=spec.is_critical,
        )

    def _eval_scale(
        self,
        spec: VerificationTestSpec,
        exec_result: ExecutionResult,
    ) -> VerificationTestResult:
        """Scale test: check that numeric result values are within expected range."""
        if spec.numeric_min is None and spec.numeric_max is None:
            return VerificationTestResult(
                test_type="scale",
                status="skip",
                actual_outcome="No numeric range specified.",
                is_critical=spec.is_critical,
            )

        rows = exec_result.rows
        if not rows:
            return VerificationTestResult(
                test_type="scale",
                status="skip",
                actual_outcome="No rows to check.",
                is_critical=spec.is_critical,
            )

        violations: list[str] = []
        for row in rows:
            for val in row:
                if not isinstance(val, (int, float)):
                    continue
                if spec.numeric_min is not None and val < spec.numeric_min:
                    violations.append(f"{val} < min({spec.numeric_min})")
                if spec.numeric_max is not None and val > spec.numeric_max:
                    violations.append(f"{val} > max({spec.numeric_max})")

        if not violations:
            bounds = []
            if spec.numeric_min is not None:
                bounds.append(f"min={spec.numeric_min}")
            if spec.numeric_max is not None:
                bounds.append(f"max={spec.numeric_max}")
            return VerificationTestResult(
                test_type="scale",
                status="pass",
                actual_outcome=(
                    f"All numeric values within expected range ({', '.join(bounds)})."
                ),
                is_critical=spec.is_critical,
            )
        sample = violations[:3]
        return VerificationTestResult(
            test_type="scale",
            status="fail",
            actual_outcome=(
                f"Out-of-range values: {sample}. May indicate wrong column or unit."
            ),
            is_critical=spec.is_critical,
        )

    # ------------------------------------------------------------------
    # Expensive test implementations (LLM-judged)
    # ------------------------------------------------------------------

    async def _eval_column_alignment(
        self,
        spec: VerificationTestSpec,
        sql: str,
        exec_result: ExecutionResult,
    ) -> VerificationTestResult:
        """Column alignment: LLM judges whether SELECT columns answer the question.

        This is an expensive test — makes 1 LLM call (model_fast).
        Runs on every fix iteration (run_expensive is always True in QueryFixer).
        """
        logger.debug("Running expensive test: column_alignment")
        select_match = re.search(
            r"SELECT\s+(.*?)\s+FROM\b",
            sql,
            re.IGNORECASE | re.DOTALL,
        )
        select_clause = select_match.group(1).strip() if select_match else sql[:200]
        sample_row = str(exec_result.rows[0]) if exec_result.rows else "(empty result)"

        prompt = (
            f"Verification: Column Alignment Check\n"
            f"Description: {spec.description}\n\n"
            f"SELECT clause: {select_clause}\n"
            f"Sample result row: {sample_row}\n\n"
            f"Expected outcome: {spec.expected_outcome}\n\n"
            "Do the selected columns actually answer the question? "
            "Reply with exactly 'PASS' or 'FAIL' on the first line, then a brief explanation."
        )

        try:
            client = get_client()
            response = await client.generate(
                model=settings.model_fast,
                system=[CacheableText(text="You are an SQL quality analyst.", cache=False)],
                messages=[{"role": "user", "content": prompt}],
                tools=[],
                temperature=0.0,
                max_tokens=200,
            )
            judgment = (response.text or "").strip().upper()
            if judgment.startswith("PASS"):
                logger.debug("column_alignment: PASS — %s", (response.text or "")[:100])
                return VerificationTestResult(
                    test_type="column_alignment",
                    status="pass",
                    actual_outcome=f"LLM judgment: {(response.text or '')[:200]}",
                    is_critical=spec.is_critical,
                )
            elif judgment.startswith("FAIL"):
                logger.info(
                    "column_alignment: FAIL — %s", (response.text or "")[:200]
                )
                return VerificationTestResult(
                    test_type="column_alignment",
                    status="fail",
                    actual_outcome=f"LLM judgment: {(response.text or '')[:200]}",
                    is_critical=spec.is_critical,
                )
            logger.warning(
                "column_alignment: inconclusive LLM response — %s",
                (response.text or "")[:100],
            )
            return VerificationTestResult(
                test_type="column_alignment",
                status="skip",
                actual_outcome=f"Inconclusive LLM response: {(response.text or '')[:100]}",
                is_critical=spec.is_critical,
            )
        except LLMError as exc:
            logger.warning("column_alignment LLM call failed: %s", exc)
            return VerificationTestResult(
                test_type="column_alignment",
                status="error",
                actual_outcome=f"LLM error: {exc}",
                is_critical=spec.is_critical,
            )

    async def _eval_boundary(
        self,
        spec: VerificationTestSpec,
        sql: str,
    ) -> VerificationTestResult:
        """Boundary test: LLM checks if date/time constraints match the question.

        This is an expensive test — makes 1 LLM call (model_fast).
        Runs on every fix iteration (run_expensive is always True in QueryFixer).
        """
        logger.debug("Running expensive test: boundary")
        where_match = re.search(
            r"\bWHERE\b(.*?)(?:\bGROUP\s+BY\b|\bORDER\s+BY\b|\bHAVING\b|\bLIMIT\b|$)",
            sql,
            re.IGNORECASE | re.DOTALL,
        )
        where_clause = where_match.group(1).strip() if where_match else "(no WHERE clause)"

        prompt = (
            f"Verification: Boundary/Date Check\n"
            f"Description: {spec.description}\n\n"
            f"WHERE clause: {where_clause}\n\n"
            f"Expected outcome: {spec.expected_outcome}\n\n"
            "Do the date/time/boundary conditions match what the question asks for? "
            "Reply with exactly 'PASS' or 'FAIL' on the first line, then a brief explanation."
        )

        try:
            client = get_client()
            response = await client.generate(
                model=settings.model_fast,
                system=[CacheableText(text="You are an SQL quality analyst.", cache=False)],
                messages=[{"role": "user", "content": prompt}],
                tools=[],
                temperature=0.0,
                max_tokens=200,
            )
            judgment = (response.text or "").strip().upper()
            if judgment.startswith("PASS"):
                status = "pass"
                logger.debug("boundary: PASS — %s", (response.text or "")[:100])
            elif judgment.startswith("FAIL"):
                status = "fail"
                logger.info("boundary: FAIL — %s", (response.text or "")[:200])
            else:
                status = "skip"
                logger.warning(
                    "boundary: inconclusive LLM response — %s",
                    (response.text or "")[:100],
                )
            return VerificationTestResult(
                test_type="boundary",
                status=status,
                actual_outcome=f"LLM judgment: {(response.text or '')[:200]}",
                is_critical=spec.is_critical,
            )
        except LLMError as exc:
            logger.warning("boundary LLM call failed: %s", exc)
            return VerificationTestResult(
                test_type="boundary",
                status="error",
                actual_outcome=f"LLM error: {exc}",
                is_critical=spec.is_critical,
            )

    def _eval_symmetry(
        self,
        spec: VerificationTestSpec,
        exec_result: ExecutionResult,
        db_path: str,
    ) -> VerificationTestResult:
        """Symmetry test: verify an aggregate total equals the sum of sub-groups.

        Classified as an expensive test and runs on every fix iteration alongside
        column_alignment and boundary (run_expensive is always True in QueryFixer).
        Unlike column_alignment and boundary, this test makes NO LLM calls — it
        executes a complementary SQL query against the raw database and compares
        the first numeric value to the candidate result within a 1% tolerance.

        When to use: questions like "how many total X?" where the LLM plan can
        supply a verification_sql that computes the expected total a different way
        (e.g. sum of sub-groups). Applicable to roughly <10% of BIRD questions.

        Requires spec.verification_sql to be set; returns "skip" otherwise.
        """
        logger.debug("Running expensive test: symmetry")

        if not spec.verification_sql:
            logger.debug("symmetry: skip — no verification_sql provided")
            return VerificationTestResult(
                test_type="symmetry",
                status="skip",
                actual_outcome="No verification_sql provided for symmetry check.",
                is_critical=spec.is_critical,
            )

        vr = execute_sql(db_path, spec.verification_sql)
        if not vr.success or not vr.rows:
            logger.warning(
                "symmetry: verification SQL failed — %s", vr.error
            )
            return VerificationTestResult(
                test_type="symmetry",
                status="error",
                actual_outcome=f"Symmetry verification SQL failed: {vr.error}",
                is_critical=spec.is_critical,
            )

        # Extract first numeric value from the candidate result
        main_val: Optional[float] = None
        for val in (exec_result.rows[0] if exec_result.rows else []):
            if isinstance(val, (int, float)):
                main_val = float(val)
                break

        # Extract first numeric value from the symmetry verification result
        check_val: Optional[float] = None
        for val in vr.rows[0]:
            if isinstance(val, (int, float)):
                check_val = float(val)
                break

        if main_val is None or check_val is None:
            logger.debug(
                "symmetry: skip — could not extract numeric values "
                "(main_val=%s, check_val=%s)", main_val, check_val
            )
            return VerificationTestResult(
                test_type="symmetry",
                status="skip",
                actual_outcome="Could not extract numeric values for symmetry comparison.",
                is_critical=spec.is_critical,
            )

        tolerance = max(abs(main_val) * 0.01, 0.01)
        if abs(main_val - check_val) <= tolerance:
            logger.debug(
                "symmetry: PASS — main=%s matches check=%s (tolerance=%.4f)",
                main_val, check_val, tolerance,
            )
            return VerificationTestResult(
                test_type="symmetry",
                status="pass",
                actual_outcome=(
                    f"Main result {main_val} matches symmetry check {check_val}."
                ),
                is_critical=spec.is_critical,
            )

        logger.info(
            "symmetry: FAIL — main=%s, check=%s, delta=%.4f (tolerance=%.4f). "
            "Result may be overcounting or undercounting.",
            main_val, check_val, abs(main_val - check_val), tolerance,
        )
        return VerificationTestResult(
            test_type="symmetry",
            status="fail",
            actual_outcome=(
                f"Symmetry mismatch: main={main_val}, check={check_val}. "
                "Result may be overcounting or undercounting."
            ),
            is_critical=spec.is_critical,
        )

    # ------------------------------------------------------------------
    # Confidence adjustment
    # ------------------------------------------------------------------

    def _compute_adjustment(
        self,
        results: list[VerificationTestResult],
    ) -> float:
        """Compute confidence score adjustment from test results."""
        if not results:
            return 0.0

        adjustment = 0.0
        for r in results:
            if r.status == "fail":
                adjustment += _PENALTY_CRITICAL if r.is_critical else _PENALTY_MINOR

        # Bonus if all non-error tests passed
        non_error = [r for r in results if r.status != "error"]
        if non_error and all(r.status in ("pass", "skip") for r in non_error):
            passed = [r for r in non_error if r.status == "pass"]
            if passed:
                adjustment = min(adjustment + _BONUS_ALL_PASS, _MAX_BONUS)

        return adjustment
